  File "/home/runner/work/resume_builder5/resume_builder5/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 504, in build_recipes
    recipe.build_arch(arch)
  File "/home/runner/work/resume_builder5/resume_builder5/p4a-recipes/reportlab/__init__.py", line 33, in build_arch
    raise RuntimeError(

RuntimeError: ReportLab source directory was not found: /home/runner/work/resume_builder5/resume_builder5/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/reportlab/arm64-v8a__ndk_target_24/reportlab/reportlab
# Command failed: ['/opt/hostedtoolcache/Python/3.11.7/x64/bin/python', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=resumebuilder', '--bootstrap=sdl2', '--requirements=python3==3.11.7,kivy==2.3.0,kivymd==1.2.0,pillow,reportlab', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--local-recipes', '/home/runner/work/resume_builder5/resume_builder5/p4a-recipes', '--color=always', '--storage-dir=/home/runner/work/resume_builder5/resume_builder5/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=24', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SELENIUM_JAR_PATH = '/usr/share/java/selenium-server.jar'
#     CONDA = '/usr/share/miniconda'
#     GITHUB_WORKSPACE = '/home/runner/work/resume_builder5/resume_builder5'
#     JAVA_HOME_11_X64 = '/usr/lib/jvm/temurin-11-jdk-amd64'
#     JAVA_HOME_25_X64 = '/usr/lib/jvm/temurin-25-jdk-amd64'
#     PKG_CONFIG_PATH = '/opt/hostedtoolcache/Python/3.11.7/x64/lib/pkgconfig'
#     GITHUB_PATH = '/home/runner/work/_temp/_runner_file_commands/add_path_c8435a70-e2bd-41e7-9102-bf229d445b4f'
#     GITHUB_ACTION = '__run_10'
#     JAVA_HOME = '/usr/lib/jvm/temurin-17-jdk-amd64'
#     GITHUB_RUN_NUMBER = '4'
#     RUNNER_NAME = 'GitHub Actions 1000000084'
#     GRADLE_HOME = '/usr/share/gradle-9.6.1'
#     GITHUB_REPOSITORY_OWNER_ID = '166769804'
#     ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE = '/opt/actionarchivecache'
#     XDG_CONFIG_HOME = '/home/runner/.config'
#     Python_ROOT_DIR = '/opt/hostedtoolcache/Python/3.11.7/x64'
#     DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
#     ANT_HOME = '/usr/share/ant'
#     JAVA_HOME_8_X64 = '/usr/lib/jvm/temurin-8-jdk-amd64'
#     GITHUB_TRIGGERING_ACTOR = 'wondxpt'
#     pythonLocation = '/opt/hostedtoolcache/Python/3.11.7/x64'
#     GITHUB_REF_TYPE = 'branch'
#     HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS = '3650'
#     ACTIONS_RUNNER_RETURN_JOB_RESULT_FOR_HOSTED = '1'
#     ANDROID_NDK = '/usr/local/lib/android/sdk/ndk/27.3.13750724'
#     BOOTSTRAP_HASKELL_NONINTERACTIVE = '1'
#     PWD = '/home/runner/work/resume_builder5/resume_builder5'
#     PIPX_BIN_DIR = '/opt/pipx_bin'
#     LOGNAME = 'runner'
#     GITHUB_ARTIFACTS_LIST = '/home/runner/work/_temp/_runner_file_commands/artifacts_list_c8435a70-e2bd-41e7-9102-bf229d445b4f'
#     GITHUB_REPOSITORY_ID = '1316473229'
#     GITHUB_ACTIONS = 'true'
#     USE_BAZEL_FALLBACK_VERSION = 'silent:'
#     ANDROID_NDK_LATEST_HOME = '/usr/local/lib/android/sdk/ndk/29.0.14206865'
#     SYSTEMD_EXEC_PID = '1878'
#     GITHUB_SHA = '443aef89d78ad563fa60abc6b3540391186cce40'
#     GITHUB_WORKFLOW_REF = 'wondxpt/resume_builder5/.github/workflows/build.yml@refs/heads/main'
#     POWERSHELL_DISTRIBUTION_CHANNEL = 'GitHub-Actions-Linux'
#     RUNNER_ENVIRONMENT = 'github-hosted'
#     DOTNET_MULTILEVEL_LOOKUP = '0'
#     GITHUB_REF = 'refs/heads/main'
#     RUNNER_OS = 'Linux'
